[package]
name = "inspect"
version = "0.1.0"
edition = "2024"

[dependencies]
ctor = "0.5.0"
env_logger = "0.11.8"
nom = "8.0.0"
nom-language = "0.1.0"
struple = "0.2.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
